import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from "@/components/ui/toaster"
import Provider from '@/components/Provider'
import { ThemeProvider } from '@/components/theme-provider'
import Topbar from '@/components/Navigation/Topbar'
import LeftSideBar from '@/components/Navigation/LeftSideBar'
import RightSideBar from '@/components/Navigation/RightSideBar'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            {session ? (
              <>
                <Topbar />
                <main className='container h-auto relative flex justify-center gap-3'>
                  <LeftSideBar />

                  {children}

                  <RightSideBar />
                </main>
              </>
            ) : (
              <>
                {children}
              </>
            )}

            <Toaster />
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  )
}
